on:
  workflow_call:
    inputs:
      publish:
        type: string
        required: false
        description: "Publish? (y/sha/N)"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PUBLISH_CHANNEL: ${{ github.event.inputs.publish == 'y' && 'latest' || 'sha' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm exec pkgts typecheck
      - run: npm exec pkgts test
      - run: npm exec pkgts build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.publish == 'y' || github.event.inputs.publish == 'sha' }}
    concurrency:
      group: publish
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Publish
        run: |
          npm publish \
            --access public \
            --tag ${{ github.event.inputs.publish == 'y' && 'latest' || 'sha' }}
        working-directory: dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Tag
        if: ${{ github.event.inputs.publish == 'y' }}
        run: git tag v$(cat dist/package.json | grep '"version"' | awk '{print$2}' | sed 's/[",]//g')
      - uses: ad-m/github-push-action@master
        if: ${{ github.event.inputs.publish == 'y' }}
        with:
          tags: true
